version: "3"

rpc:
  listen: "tcp://0.0.0.0:6001"
logs:
  channels:
    app:
      level: info
server:
  command: "php server.php"
  relay: pipes
http:
  address: "0.0.0.0:9501"
  middleware:
    - gzip
    - headers
  headers:
    cors:
      allowed_origin: "*"
      allowed_headers: "*"
      allowed_origin_regex: "^https?://.*"
      allowed_methods: "GET,POST,PUT,DELETE,OPTIONS"
      exposed_headers: "Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma"
      max_age: 600
      options_success_status: 200
      debug: false
  pool:
    debug: true
    num_workers: 1
    supervisor:
      max_worker_memory: 256 # 256MB memory limit per worker (Soft limit)
      exec_ttl: 60s # Maximum time a single job can run (Hard limit)
      ttl: 3600s # How long a worker can live (Soft limit)
