version: '3.8'

services:
  esi-proxy:
    image: ghcr.io/eve-kill/esi-proxy:latest
    ports:
      - "9501:9501"
    environment:
      - OWNER=${OWNER}
      - DIAL_HOME=${DIAL_HOME}
      - EXTERNAL_ADDRESS=${EXTERNAL_ADDRESS}
    volumes:
      - ./esi-proxy-name:/tmp/esi-proxy.name
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
