services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --save "" --appendonly no --maxmemory 1024mb
    networks:
      - internal

  esiproxy:
    image: ghcr.io/eve-kill/esi-proxy:latest
    container_name: esiproxy
    environment:
      HOST=0.0.0.0
      PORT=9501
      EXTERNAL_ADDRESS=http://IP:9501
      DIAL_HOME=true
      OWNER=Name
      REDIS_HOST=127.0.0.1
      REDIS_PORT=6379
      REDIS_PASSWORD=
      REDIS_DATABASE=0
    volumes:
      - /tmp:/tmp
    ports:
      - 9501:9501
    networks:
      - internal
    depends_on:
      - redis
